Vite\ViteAssetLoader:
  arguments:
    - "%kernel.project_dir%/public/assets/manifest.json"
    - "%env(VITE_ASSETS_PATH)%"
    - "%env(VITE_DEV_SERVER_URL)%"
    - "%env(VITE_ENV)%"
    - "%env(VITE_REACT)%"

Vite\ViteManifestReader:
  class: Vite\ViteManifestReader

Vite\Symfony\Twig\TwigAssetExtension:
  class: Vite\Symfony\Twig\TwigAssetExtension